# 디렉토리설정

In [ ]:
import os

In [10]:
os.getcwd()

'C:\\Users\\chang'

In [14]:
path=os.getcwd()

'C:\\Users\\chang'

In [12]:
os.chdir(path)

In [16]:
os.chdir("D:")
os.getcwd()

'D:\\'

In [18]:
print(os.path.join("/Users/evan/dev/python/web-crawler-py/parsed_data/", "test"))

/Users/evan/dev/python/web-crawler-py/parsed_data/test


In [9]:
def search(dirname):
    filenames = os.listdir(dirname)
    for filename in filenames:
        full_filename = os.path.join(dirname, filename)
        print (full_filename)

search("D:/")

D:/$RECYCLE.BIN
D:/3D
D:/3D model
D:/3차원 stl
D:/3차원 시스템
D:/3차원모델(시스템)
D:/alsdream
D:/alsdream.egg
D:/Image Files
D:/man(stl)
D:/man(stl).zip
D:/RotationCapture(man)
D:/RotationCapture(woman)
D:/sample1.ply
D:/System Volume Information
D:/tensorflow2
D:/tensorflow2.egg
D:/unet
D:/woman(stl)
D:/woman(stl).zip
D:/데이터전처리
D:/인체3차원데이터


# 데이터만들기

In [3]:
import pandas as pd
import numpy as np

In [4]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
array = np.array([[1, 2, 3], [4, 5, 6]]).reshape((3,2))

In [55]:
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
array = np.array(range(20)).reshape((5,4))

In [51]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
df = pd.DataFrame(array)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
df

A
0  4
1  5
2  6
3  7

In [10]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [1, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  1  5  6
2  7  8  9

In [22]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [1, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'], index=["A","B","C"])
df

A  B  C
A  1  2  3
B  1  5  6
C  7  8  9

In [23]:
df2 = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index= [2.5, 12.6, 4.8], columns=[48, 49, 50])
display(df2)

48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9

In [24]:
df.drop('A', axis=1, inplace=True)

In [25]:
df

B  C
A  2  3
B  5  6
C  8  9

In [26]:
df3 = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [40, 50, 60], [23, 35, 37]]), 
                  index= [2.5, 12.6, 4.8, 4.8, 2.5], 
                  columns=[48, 49, 50])

In [27]:
df3

48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [31]:
df3 = df3.reset_index() #index를 변수로 변환하고 다시 새로운 index를 앞에 추가한다.
df3

level_0  index  48  49  50
0        0    2.5   1   2   3
1        1   12.6   4   5   6
2        2    4.8   7   8   9
3        3    4.8  40  50  60
4        4    2.5  23  35  37

In [46]:
df2

48  49  50  49
2.5    1   2   3   6
12.6   4   5   6   6
4.8    7   8   9   6

### 변수추가

In [47]:
df2["49"]=6
df2

48  49  50  49
2.5    1   2   3   6
12.6   4   5   6   6
4.8    7   8   9   6

In [54]:
variable=[201142,201451,201215]
df2["학번"]=variable
df2

48  49  50  49      학번
2.5    1   2   3   6  201142
12.6   4   5   6   6  201451
4.8    7   8   9   6  201215

In [57]:
df2=df2.drop([2.5, 12.6])

In [58]:
df2

48  49  50  49      학번
4.8   7   8   9   6  201215

columns=변수, index=데이터의 이름

In [90]:
df4 = pd.DataFrame(data=np.array([[1,2,3],[2,4,5],[5,6,7],[2,4,6]]), columns=["A","B","C"], index=["국어","영어","수학","과학"])
df4

A  B  C
국어  1  2  3
영어  2  4  5
수학  5  6  7
과학  2  4  6

In [81]:
df4=df4.drop(["국어"])
df4

A  B  C
영어  2  4  5
수학  5  6  7
과학  2  4  6

In [95]:
df5=df4[df4["A"]==2].index #조건에 포함되는 데이터 삭제
df6=df4.drop(df5)

A  B  C
국어  1  2  3

In [111]:
a=df4[(df4["A"]>2) | (df4["B"]>2)].index #조건에 포함되는 데이터 삭제
df6=df4.drop(a)

In [113]:
new=[(2,3,4),(5,6,7)]
new_data=pd.DataFrame(new, columns=df6.columns, index=["중국어","아랍어"])

In [114]:
new_data

A  B  C
중국어  2  3  4
아랍어  5  6  7

In [118]:
df6=df6.append(new_data)
df6

A  B  C
국어   1  2  3
중국어  2  3  4
아랍어  5  6  7
중국어  2  3  4
아랍어  5  6  7